'use strict';
const payConfig = require('../../../config/pay/payConfig')

export const payServer = {//支付服务器
    domainName: payConfig.domainname,//服务器地址
    port: 9999,//支付服务器端口
    path: {
        1: 'pay1',//块一付发起请求地址
        2: 'api/sandsPay/XYSHWEB/prePay',//烜洋平台
        3: 'api/sandsPay/JX/prePay',//吉象
        4: 'api/sandsPay/Shanfto/prePay',//星闪付
        5: 'pay5',//北京发起请求地址
        6: 'pay6',//天明2发起请求地址
        7: 'pay7',//MOL发起请求地址
        8: 'pay8',//SKLD发起请求地址
        9: 'pay9',//hec钱包发起请求地址
        10: 'pay10',//柬埔寨自营(弹弹)发起请求地址
        11: 'pay11',//柬埔寨自营(paysApi)发起请求地址
        12: 'pay12',//bluePay支付请求地址
        13: 'pay13',//MW支付请求地址
        14: 'pay14',//多牛支付请求地址
        15: 'pay15',//bufPay支付请求地址
        16: 'pay16',//竣付通支付请求地址
        17: 'pay17',//AAA支付请求地址
        18: 'pay18',//棋牌支付请求地址
        19: 'pay19',//宝付支付请求地址
        20: 'pay20',//福会通支付请求地址
        22: 'pay22',//锋胜支付请求地址
        23: 'pay23',//烜洋支付请求地址
        24: 'pay24',//星染支付
        25: 'pay25',//彩付支付
        27: 'pay27',//易友支付
        28: 'pay28',//云付支付
        29: 'pay29',//涉月宝支付
        30: 'pay30',//华付支付
        31: 'pay31',//海天支付
        33: 'pay33',//呱呱支付
        34: 'pay34',//娱付宝
        35: 'pay35',//收付通
        36: 'pay36',//云威
        37: 'pay37',//优选
        38: 'pay38',//宝付支付宝
        39: 'pay39',//聚宝付
        40: 'pay40',//店员通支付
        41: 'pay41',//全速支付
        42: 'pay42',//聚辉支付
        43: 'pay43',//易信支付
        44: 'pay44',//捷付通
        45: 'pay45',//天成支付
        46: 'pay46',//芒果支付
        47: 'pay47',//快捷支付
        48: 'pay48',//陆付宝支付
        49: 'pay49',//信速支付
        50: 'pay50',//皇家666支付
        51: 'pay51',//北京易支付
        52: 'pay52',//顶盛金服
        53: 'pay53',//众赢支付
        54: 'api/blockChain/Otc/prePay',
        55: 'api/blockChain/Otc/prePay',
        56: 'api/sandsPay/DYT/prePay',
        57: 'api/sandsPay/DYT/prePay',
        58: 'api/sandsPay/cheng/prePay',
        59: 'api/sandsPay/cheng/prePay',
        60: 'api/sandsPay/YLF/prePay',
        61: 'api/sandsPay/YLF/prePay',
        62: 'api/sandsPay/HKF/prePay',
        63: 'api/sandsPay/AJ/prePay',
        64: 'api/sandsPay/THB/prePay',
        65: 'api/sandsPay/xlz/prePay',
        66: 'api/sandsPay/Spark/prePay',
        67: 'api/sandsPay/Itzoon/prePay',
        68: 'api/sandsPay/xlz/prePay',
        69: 'api/commonPay/Y/prePay',
        70: 'api/commonPay/JF/prePay',
        71: 'api/commonPay/XK/prePay',
        72: 'api/payment/js/prePay',
    },
    path2: 'integral'
};